[package]
name = "rtsp-camera-mock"
version = "0.1.0"
authors = ["Valmir Pretto <valmir.pretto@deepx.it>"]
edition = "2018"

[dependencies]
glib = { version = "0.9.0" }
gstreamer = { version = "0.15.0" }
gstreamer-rtsp-server = { version = "0.15.0" }
